baseURL = "https://blog.belavadi.com/"
languageCode = "en-us"
title = "Prahalad Belavadi's blog"
theme = "github-style"
# googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Prahalad Belavadi"
  description = "Mostly Curation of what I think and find fascinating"
  github = "prahaladbelavadi"
  facebook = "prahaladbelavadi"
  twitter = "prahaladbelavad"
  linkedin = "prahaladbelavadi"
  instagram = "prahaladbelavadi"
#   tumblr = "MeiK2333"
  email = "git-blog@belavadi.com"
  url = "https://belavadi.com"
#   keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/github.png"
  location = "03FF431A9B5E171DAF868252CD2EC902603B9E22"

  [[params.links]]
    title = "Medium"
    href = "https://github.com/Prahaladbelavadi"
    icon = "https://blog.belavadi.com/images/medium.png"
  [[params.links]]
    title = "Link2"
    href = "https://belavadi.com"
    icon = "https://blog.belavadi.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
